# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from gui.qrc import chat_rc

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(641, 411)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/pikaqiu.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.pushButton_search = QtWidgets.QPushButton(Form)
        self.pushButton_search.setGeometry(QtCore.QRect(540, 40, 81, 51))
        self.pushButton_search.setObjectName("pushButton_search")
        self.textEdit_input = QtWidgets.QTextEdit(Form)
        self.textEdit_input.setGeometry(QtCore.QRect(20, 40, 501, 51))
        self.textEdit_input.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit_input.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_input.setObjectName("textEdit_input")
        self.textEdit_out = QtWidgets.QTextEdit(Form)
        self.textEdit_out.setGeometry(QtCore.QRect(20, 110, 601, 261))
        self.textEdit_out.setObjectName("textEdit_out")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ChatGpt搜索"))
        self.pushButton_search.setText(_translate("Form", "搜 索"))
        self.textEdit_input.setPlaceholderText(_translate("Form", "输入指令"))
        self.textEdit_out.setPlaceholderText(_translate("Form", "输出"))
# import chat_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
